defaults: &defaults
  redis:
    host:     <%= ENV.fetch('REDIS_HOST')     { localhost } %>
    port:     <%= ENV.fetch('REDIS_PORT')     { 6379 } %>
    password: <%= ENV.fetch('REDIS_PASSWORD') { nil } %>

  jira:
    connection:
      username: <%= ENV.fetch('JIRA_USER') { username } %>
      password: <%= ENV.fetch('JIRA_PASS') { password } %>
      site:     <%= ENV.fetch('JIRA_SITE') { https://xxxx.atlassian.net:443 } %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
