defaults: &defaults
  jira:
    connection:
      username: user
      password: password
      site:     https://xxxx.atlassian.net:443
    board:
      - Product Backlog
      - Sprint Backlog
      - Doing
      - Code Review
      - Testing
      - Waiting to Deploy
      - Done

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
