defaults: &defaults
  jira:
    connection:
      username: user
      password: password
      site:     https://xxxx.atlassian.net:443

    project_key: XXX

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
